name: cmsv
channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults

dependencies:
  - python=3.9

  # GPU PyTorch stack. The nvidia channel is required for pytorch-cuda.
  - pytorch=2.5.1
  - pytorch-cuda=12.1

  - numpy
  - pandas
  - scipy
  - scikit-learn
  - tqdm
  - packaging
  - ninja
  - wheel
  - setuptools
  - pip
