name: cmsv
channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults

dependencies:
  - python=3.10

  # GPU PyTorch stack. The nvidia channel is required for pytorch-cuda.
  - pytorch=2.1.*
  - pytorch-cuda=12.1

  - numpy
  - pandas
  - scipy
  - scikit-learn
  - tqdm
  - pip
  - pip:
      - pysam
      - mamba-ssm
      - causal-conv1d
